version : "3"
services:
    backend:
        build: ./java-docker/
        volumes:
            - './java-docker/backend-app:/app/backend-app'
            - './java-docker/maven:/root/.m2'
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.4"
                    memory: 1024M
            restart_policy:
                condition: on-failure
        environment:
            - MAINDB=${MYSQL_DATABASE}
            - JAVA_USER=${MYSQL_USER}
            - JAVA_PASS=${MYSQL_PASSWORD}
            - JAVA_SERVER_PORT=${JAVA_SERVER_PORT}
            - JAVA_DEBUG_PW=${JAVA_DEBUG_PW}
            - SPRING_PROFILES_ACTIVE=dev,docker,swagger
            - MAVEN_OPTS=-Xnoagent -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        ports:
            - "8080:8080"
            - "5005:5005"
        depends_on:
            - db
            - redis
        networks:
            - webnet
    vue:
        build: ./vue-docker/
        volumes:
            - './vue-docker/frontend-app:/app/js'
            - './logs:/root/.npm/_logs'
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 512M
            restart_policy:
                    condition: on-failure
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=4444
        depends_on:
            - backend
        ports:
            - "4444:4444"

        networks:
            - webnet
            
    redis:
        image: redis:5.0.3
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 200M
            restart_policy:
                condition: on-failure
        ports:
            - "6379:6379"
        networks:
            - webnet
            
    db:
        build: ./db-docker/
        volumes:
            - './db-docker/data:/var/lib/mysql'
            - './db-docker/init-scripts:/docker-entrypoint-initdb.d'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.4"
                    memory: 1024M
            restart_policy:
                condition: on-failure
        restart: always
        ports:
            - "3306:3306"
        networks:
            - webnet
networks:
    webnet: