version : "3"
services:
    backend:
        # image: suti211/python-tut:flaskapp
        build: ./python-docker/
        volumes:
            - './python-docker/pysource:/app/pytarget' 
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        restart: always
        ports:
            - "4000:4000"
        depends_on:
            - redis
        networks:
            - webnet
    vue:
        build: ./vue-docker/
        volumes:
            - './vue-docker/frontend-app:/app/js'
            - './logs:/root/.npm/'
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 512M
            restart_policy:
                    condition: on-failure
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=8000
        ports:
            - "80:8000"
        depends_on:
            - backend
        networks:
            - webnet
    redis:
        image: redis:5.0.3
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 200M
            restart_policy:
                condition: on-failure
        ports:
            - "6379:6379"
        networks:
            - webnet
networks:
    webnet:
        
