version : "3"
services:
    backend:
        build: ./java-docker/
        volumes:
            - './java-docker/backend-app:/app/backend-app'
        environment:
            - MAINDB=${MYSQL_DATABASE}
            - JAVA_USER=${MYSQL_USER}
            - JAVA_PASS=${MYSQL_PASSWORD}
            - SPRING_PROFILES_ACTIVE=dev,docker,swagger
        ports:
            - "8080:8443"
        depends_on:
            - redis
        networks:
            - webnet
    ng:
        build: ./ng-docker/
        volumes:
            - './ng-docker/frontend-app:/app'
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=8000
        ports:
            - "8000:4200"
        depends_on:
            - backend
        networks:
            - webnet
            
    redis:
        image: redis:5.0.3
        ports:
            - "6379:6379"
        networks:
            - webnet
            
    db:
        build: ./db-docker/
        volumes:
            - './db-docker/data:/var/lib/mysql'
            - './db-docker/init-scripts:/docker-entrypoint-initdb.d'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        restart: always
        ports:
            - "3306:3306"
        networks:
            - webnet
networks:
    webnet: