FROM ubuntu:16.04

RUN export DEBIAN_FRONTEND=noninteractive && \
	apt-get update && \
	apt-get install -y \
	software-properties-common apt-utils curl
	
RUN export DEBIAN_FRONTEND=noninteractive && \
	add-apt-repository ppa:webupd8team/java && \
	apt-get update && \
	echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections && \
	apt-get install -y \
	oracle-java8-installer \
	git \
	maven sudo
	
ADD entry.sh /entry.sh

RUN chmod 755 /*.sh

WORKDIR /app

ENV SPRING_PROFILES_ACTIVE=dev,docker

EXPOSE 8080:8080
CMD ["/entry.sh"]