version : "3"
services:
    web:
        image: suti211/python-tut:flaskapp
        volumes:
            - './pysource:/app/pytarget' 
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure
        ports:
            - "4000:80"
        networks:
            - webnet
    redis:
        image: redis:5.0.3
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 200M
            restart_policy:
                condition: on-failure
        ports:
            - "6379:6379"
        networks:
            - webnet
networks:
    webnet:
        